url: https://test-stand.gb.ru/api/posts
address_post: https://test-stand.gb.ru/gateway/posts

username: Fred123
password: 17fe38c02d

username2: GB202310991170
password2: b33663109a

title: Заголовок
description: Описание
content: Содержание
